### ISSUE TITLE
the clang compiler does not support '-march=native'

### ISSUE THREAD

**Issue by jefflyne** [yoshoku/annoy.rb#2]
I'm using a Macbook Air with an Apple M1 chip. I don't know anything about clang so I can't debug this on my own. Annoy installs fine with pip but I need it in a ruby project, not python. Thanks for your effort in making the gem.

Installing annoy-rb 0.4.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory: /Users/airrr/.rvm/gems/ruby-2.6.8/gems/annoy-rb-0.4.0/ext/annoy
/Users/airrr/.rvm/rubies/ruby-2.6.8/bin/ruby -I
/Users/airrr/.rvm/rubies/ruby-2.6.8/lib/ruby/site_ruby/2.6.0 -r ./siteconf20211125-29838-nx1av.rb
extconf.rb
checking for -lstdc++... yes
creating Makefile

current directory: /Users/airrr/.rvm/gems/ruby-2.6.8/gems/annoy-rb-0.4.0/ext/annoy
make "DESTDIR=" clean

current directory: /Users/airrr/.rvm/gems/ruby-2.6.8/gems/annoy-rb-0.4.0/ext/annoy
make "DESTDIR="
compiling annoyext.cpp
clang: error: the clang compiler does not support '-march=native'
make: *** [annoyext.o] Error 1

**Comment by yoshoku** [comment]
@jefflyne I have released the annoy-rb without the optimization options as version 0.5.0: https://github.com/yoshoku/annoy.rb/blob/main/CHANGELOG.md#050
