### ISSUE TITLE
dtype float32 isn't supported properly

### ISSUE THREAD

**Issue by gyver** [yoshoku/annoy.rb#3]
We tried to switch from the default dtype (float64) to float32 in order to reduce memory usage and maybe CPU too.

Unfortunately add_item only tests for double (not single precision float). If the item isn't a double vector (which is the case when creating an Index with dtype float32) it converts all values to integer.

Unfortunately my CPP skills are more than rusty so I didn't fix the code myself (there might be other places where the dtype isn't properly handled too).

**Comment by yoshoku** [comment]
Thank you for your report. This bug is caused by wrong ternary operator. I will fix this bug as soon as possible.
https://github.com/yoshoku/annoy-rb/blob/main/ext/annoy/annoyext.hpp#L269

**Comment by yoshoku** [comment]
@gyver I have released this bug fix as v0.7.1. Please try it.

**Comment by gyver** [comment]
I'm happy to report that v0.7.1 pass our internal tests when we configure them to use float32. Thanks @yoshoku.

**Comment by yoshoku** [comment]
Thank you for your cooperation 👍
